apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app-deployment
spec:
  selector:
    matchLabels:
      app: resume-app
  replicas: 2
  template:
    # this part represents the configuration of the pods
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-app
        image: resume-app:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: resume-app-service
spec:
  selector:
    app: resume-app
  # this is needed in order to make it an external service and not an internal service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      # needed for external services
      nodePort: 30100
